name: example
description: "An example app demonstrating the usage of the Strivacity Flutter SDK for authentication"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  strivacity_flutter:
    path: ../
  cupertino_icons: ^1.0.8
  flutter_keychain: ^2.5.0
  fluttertoast: ^8.2.12
  webview_flutter: ^4.10.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  flutter_custom_tabs: ^2.1.0
  app_links: ^6.3.3

dependency_overrides:
  strivacity_flutter_platform_interface:
    path: ../../strivacity_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
