name: strivacity_flutter
description: "Strivacity Flutter SDK"
version: 1.1.1
homepage: https://github.com/Strivacity/sdk-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  strivacity_flutter_platform_interface: ^1.0.0
  crypto: ^3.0.6
  cookie_jar: ^4.0.8
  dio: ^5.8.0
  dio_cookie_manager: ^3.2.0
  path_provider: ^2.1.5

dependency_overrides:
  strivacity_flutter_platform_interface:
    path: ../strivacity_flutter_platform_interface

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
