name: strivacity_flutter_platform_interface
description: "Strivacity Flutter SDK platform interface"
version: 1.1.0
homepage: https://github.com/Strivacity/sdk-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
