name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Run Dart Analyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Install dependencies
        run: |
          cd strivacity_flutter
          flutter pub get
          cd ../strivacity_flutter_platform_interface
          flutter pub get

      - name: Add example/.env
        working-directory: strivacity_flutter
        run: cp example/.env.example example/.env

      - name: Analyze
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-warnings: true

  build_example_android:
    name: Build Android example app
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Install dependencies
        working-directory: strivacity_flutter/example
        run: flutter pub get

      - name: Add example/.env
        working-directory: strivacity_flutter
        run: cp example/.env.example example/.env

      - name: Build
        working-directory: strivacity_flutter/example
        run: flutter build apk

  build_example_ios_stable:
    name: Build iOS example app
    runs-on: macos-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Install dependencies
        working-directory: strivacity_flutter/example
        run: flutter pub get

      - name: Add example/.env
        working-directory: strivacity_flutter
        run: cp example/.env.example example/.env

      - name: Build
        working-directory: strivacity_flutter/example
        run: flutter build ipa --no-codesign

  test:
    name: Run all unit tests
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Test
        working-directory: strivacity_flutter
        run: flutter test
